### ISSUE TITLE
Dependency fix: Upgrade webpack-dev-middleware to version 5.3.4 or later

### ISSUE THREAD

**Issue by egor-progger** [egor-progger/pointlinejs#28]
Upgrade webpack-dev-middleware to version 5.3.4 or later

**Comment by mademoiselle-chantal** [comment]
Hello, @egor-progger l would like to work on this issue.

**Comment by egor-progger** [comment]
Hello, @mademoiselle-chantal . Ok. I created new branch for this issue. Can you fork branch `28-dependency-fix-upgrade-webpack-dev-middleware-to-version-534-or-later`, and create pull request to same branch?

**Comment by mademoiselle-chantal** [comment]
Hello, @egor-progger. I would appreciate your help. When l try to push my code I get the following:

```fatal: The current branch 28-dependency-fix-upgrade-webpack-dev-middleware-to-version-534-or-later has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin 28-dependency-fix-upgrade-webpack-dev-middleware-to-version-534-or-later

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.
```

And then l run this:
```
 git push --set-upstream origin 28-dependency-fix-upgrade-webpack-dev-middleware-to-version-534-or-later
```

I hoped it could work but unfortunately, it didn't. I got the the following error:
```
remote: Permission to egor-progger/pointlinejs-quick-start.git denied to mademoiselle-chantal.
fatal: unable to access 'https://github.com/egor-progger/pointlinejs-quick-start/': The requested URL returned error: 403
```

**Comment by mademoiselle-chantal** [comment]
Can you kindly permit me so that l can be able to push the code? Thanks!

**Comment by egor-progger** [comment]
Hello, @mademoiselle-chantal . I think you have not corrent remote url for origin. I did steps from my another github accouns:
1. `git clone git@github.com:egor-progger/pointlinejs.git .` (remove dot in the end if you want to create new directory repository
2. ` git fetch origin 28-dependency-fix-upgrade-webpack-dev-middleware-to-version-534-or-later`
3. modify one file
4. commit changes
5. `git push`
You can see commit after this steps https://github.com/egor-progger/pointlinejs/commits/28-dependency-fix-upgrade-webpack-dev-middleware-to-version-534-or-later/
Also I see that you have **pointlinejs-quick-start** in error message:
```
remote: Permission to egor-progger/pointlinejs-quick-start.git denied to mademoiselle-chantal.
fatal: unable to access 'https://github.com/egor-progger/pointlinejs-quick-start/': The requested URL returned error: 403
```
it looks like you clone another repository. I created pointlinejs-quick-start only for demo PointlineJS. You need clone `git@github.com:egor-progger/pointlinejs.git` and push to it.

**Comment by mademoiselle-chantal** [comment]
Yeah, so the whole time l was cloning the wrong repo. I think you should update your README cos that's the one l was using ..here https://github.com/egor-progger/pointlinejs/blob/master/README.md

**Comment by mademoiselle-chantal** [comment]
I deleted the old repo l had and l cloned the correct one. l can see everything correct now. However, I've encountered the error below when l try to run ```npx webpack serve``` to see the app in the browser. It's opening but am seeing this

<img width="1467" alt="Screenshot 2024-03-28 at 10 01 44" src="https://github.com/egor-progger/pointlinejs/assets/120084609/618449d7-57db-4999-8ce4-afc5e8a64942">

Help me, maybe l didn't understand the error but aren't we supposed to have the ```api```  file somewhere in the ```documentation``` folder cos from my understanding the endpoint ```documenation/api``` cannot be reached here.

**Comment by mademoiselle-chantal** [comment]
Currently, l am looking for solutions on StackOverFlow, Github, and other sources to see if maybe someone out there has encountered the same issue as mine.

**Comment by mademoiselle-chantal** [comment]
Alright! I think l found the solution in no time. I used this https://stackoverflow.com/questions/63833072/error-when-trying-to-copy-an-empty-folder-with-webpack

Specifically this answer:
<img width="763" alt="Screenshot 2024-03-28 at 10 14 08" src="https://github.com/egor-progger/pointlinejs/assets/120084609/0966208c-3864-4444-9dbc-e621d5491364">

So, l modified this section in the ```webpack.config.s``` to look like so:
```
        {
          from: 'src/documentation/api',
          to: 'documentation/api',
          noErrorOnMissing: true,
        },
```

**Comment by mademoiselle-chantal** [comment]
I don't know if that's what you want. You can help me if you have better solutions than the one l found.

**Comment by mademoiselle-chantal** [comment]
I think l see where the problem is. You're using SSH keys and l use HTTP keys. So does that mean l have to transition and also use SSH keys just as you do?

**Comment by egor-progger** [comment]
> I think l see where the problem is. You're using SSH keys and l use HTTP keys. So does that mean l have to transition and also use SSH keys just as you do?

@mademoiselle-chantal you can try create own ssh key and add ssh key to your profile on github
1. create ssh key manual https://docs.github.com/ru/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
2. add ssh key manual https://docs.github.com/ru/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by egor-progger** [comment]
> Yeah, so the whole time l was cloning the wrong repo. I think you should update your README cos that's the one l was using ..here https://github.com/egor-progger/pointlinejs/blob/master/README.md

I will think about modify. About development I added **Development** (https://github.com/egor-progger/pointlinejs#development) section in readme. Quickstart is example how to run project with pointlinejs, not for development pointlinejs.

**Comment by mademoiselle-chantal** [comment]
> > I think l see where the problem is. You're using SSH keys and l use HTTP keys. So does that mean l have to transition and also use SSH keys just as you do?
> 
> @mademoiselle-chantal you can try create own ssh key and add ssh key to your profile on github
> 
> 1. create ssh key manual https://docs.github.com/ru/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
> 2. add ssh key manual https://docs.github.com/ru/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
>    or you can clone with https https://github.com/egor-progger/pointlinejs.git with command:
> 
> ```
> git clone https://github.com/egor-progger/pointlinejs.git . (remove dot in the end if you want to create new directory repository
> ```

That's the one l cloned but still, it can't allow me to push my changes.

**Comment by egor-progger** [comment]
@mademoiselle-chantal , I checked with different ssh key, and I got same error. I suggest this scheme:
1. [Fork](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) the https://github.com/egor-progger/pointlinejs repo.
2. In your forked repository, make your changes in a new git branch:
```
git clone [your forked repository url]
git fetch origin
git checkout 28-dependency-fix-upgrade-webpack-dev-middleware-to-version-534-or-later
```
3. Commit your changes. Use this template for commit message: `#[issue number]: [short description about fixes]`. In your case it is:
`#28: upgrade webpack-dev-middleware`
4. Push your branch to GitHub:
`git push origin 28-dependency-fix-upgrade-webpack-dev-middleware-to-version-534-or-later`
5. Create a pull request from your fork from branch `28-dependency-fix-upgrade-webpack-dev-middleware-to-version-534-or-later` to `pointlinejs:master`.
Later I add this instruction to README

**Comment by mademoiselle-chantal** [comment]
Thank you @egor-progger. It was my mistake all along I was cloning your repo directly not my fork. I'm so sorry.

**Comment by mademoiselle-chantal** [comment]
Alright, so l have created the PR. You can take a look.

**Comment by egor-progger** [comment]
@mademoiselle-chantal , I merge #31 , but `dependabot alerts` still has message:
```
 Upgrade webpack-dev-middleware to version 5.3.4 or later. For example:

"dependencies": {
  "webpack-dev-middleware": ">=5.3.4"
}

"devDependencies": {
  "webpack-dev-middleware": ">=5.3.4"
}
```
Did you check `webpack-dev-middleware` in package.json.lock?

**Comment by mademoiselle-chantal** [comment]
> > Yes, and it showed that it had been updated to v5.3.4. If it's not showing l can work on it again.
> > It's weird. No, thanks. I updated webpack, webpack-cli, webpack-dev-server to latest version.
> 
> I have one priority issue ##27. Do you have ideas about how to replace code in Util.ts?

Unfortunately, l don't. I'm sorry. I wish l could offer a hand.

**Comment by egor-progger** [comment]
@mademoiselle-chantal , I see, thanks. May be you can help with #7 ?
